# Name       : Felmdrav
# Version    : 0.1.0
# Released   : 2025-12-10

name = "Felmdrav"
license = "MIT"
licenselink = "https://github.com/geschke/hugo-felmdrav/blob/master/LICENSE.md"
description = "Felmfrav is a minimalistic Hugo theme, based on Bootstrap 5 framework"
homepage = "https://github.com/geschke/hugo-tikva/"
tags = ["theme", "core", "modern", "responsive", "bootstrap", "minimal", "blog", "font awesome", "white", "dark", "light" ]
features = ["responsive","blog"]
min_version = "0.100.0"

[author]
  name = "Ralf Geschke"
  homepage = "https://www.kuerbis.org"

# If porting an existing theme
[original]
  name = "Felmdraf theme for Hugo static website genrator"
  homepage = "https://www.kuerbis.org/felmdrav/"
  repo = "https://github.com/geschke/hugo-felmdrav"
